### ISSUE TITLE
feature request: generic temporal pca implementation

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#15]
target: `pca.R`

**Comment by mh105** [comment]
Would this count as analysis and thus be left out of `eyeris` for now? I'm cool either way but just want to make sure we don't slip into adding cool analysis stuff until the preprocessing package gets out.

If you two are interested in doing this in R, we could develop this together on a separate front but maybe we wouldn't want to add this as a pipeline function (if it would apply after data got epoched) for now?

**Comment by shawntz** [comment]
Good point Alex -- sticking to the design principles of "preprocessing-first" we outlined in #6, I'm going to close this issue for now. Then, once we have the preprocessing covered, I'm thinking we can add these types of analysis steps as examples showcased within various vignettes (i.e., illustrating how the preprocessed data that comes out of `eyeris` is plug-and-play with certain analysis approaches (but these analysis approaches are not _exported functions_ from `eyeris`). Sound good @mh105 and @alicexue ?

**Comment by mh105** [comment]
Yeah I very much agree with this plan. Once the preprocessing is done, we might want to discuss first what are the exact steps we want for temporal pca to include, and then writing them in an efficient implementation and visualization will be a good practice for us to 1) as a separate implementation to compare with Alice's implementation, and 2) to demonstrate the power of `eyeris`.
