### ISSUE TITLE
write documentation: `detransient.R`

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#46]

**Comment by mh105** [comment]
Is it necessary to call this function `despeed()` (i.e., is it a convention in the other packages)? To me, `detransient` feels a lot more intuitive...

**Comment by shawntz** [comment]
i am in favor of this recommendation -- to be honest, i originally chose `despeed()` because i was quickly trying to come up with 1 word verbs for each function, and it's the first thing that came to my mind for this lol 🙈

**Comment by mh105** [comment]
Sounds good - yeah I think `detransient` fits with `detrend` and `deblink`
