### ISSUE TITLE
feature request: update `lpfilt()` to implement more than the fixed filter design

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#5]

**Comment by mh105** [comment]
@shawntschwartz 
Let's design the filter with [`buttord()`](https://www.rdocumentation.org/packages/signal/versions/1.8-0/topics/buttord).

default suggestion for the lowpass filter:
`Wp=5Hz`, `Ws=10Hz`, `Rp=0.5dB`, `Rs=30dB`

After creating the filter with [`butter()`](https://www.rdocumentation.org/packages/signal/versions/1.8-0/topics/butter), use `freqz()` to visualize the frequency response.

**Comment by shawntz** [comment]
@mh105 
thanks for this contribution -- i'll soon merge this with the other issues related to the new, target `filt()` function (#2 and #4).

quick clarification question about the implementation: would you recommend making the output of `freqz()` visible to the user by default during the "interactive" step (with a flag to disable/just save out to a file for automated pipelines)?

also, can you provide some brief text that could be passed along as a recommendation to the user when evaluating their lowpass filter? 

and finally, to ensure we're on the same page, do you recommend our function essentially only providing the lowpass filter (as part of the _opinionated prescription_) -- and leave other filtering choices up to them (but not accessible from our package)?

thanks!!

**Comment by mh105** [comment]
Yes - I'll make a PR now for this. The previous comment was mostly me reminding myself what I need to do here :)

**Comment by shawntz** [comment]
perfect, thanks! 💯
