### ISSUE TITLE
feature request: before running `epoch()`, force user to run specific set of steps

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#6]
* what steps do we want to force the user to run before enabling the `epoch()` feature @hyang336?

**Comment by hyang336** [comment]
Maybe after all the preprocessing steps? Is there ever gonna be a case where that approach suboptimal compared to doing some of the steps after epoching? I can't think of one on top of my head. But we should probably also have a flag in the epoch() function to allow users to turn off  the enforcement.

**Comment by shawntz** [comment]
yeah i agree that the default behavior should be to enforce (with a flag to disable this and instead throw a warning message). 

giving it further thought, i feel like there's only 2 obvious steps that we'd want to enforce _prior to epoching_, which would be:

- `deblink()`
- `despeed()`

i think after that, the user shouldn't be bugged about further interpolating/smoothing given it may not be something they're interested in doing to their data.

though, another open question is how to handle requests to run steps after epoching, _**on the epoched data**_. as of now, this is only supported on the unepoched data within the `eyeris` object, though, it would be trivial to allow users to `z-score` etc. on epoched data... but personally i don't see an obvious need to support this as a feature at this time since most (if not all) the steps you'd ideally want to do should probably happen on the original timeseries _**and not the cut-up one**_. 

@hyang336 @mh105 -- can you guys share any opposition to this or lmk if we should proceed as planned, thx!

-s-

**Comment by hyang336** [comment]
These make sense to me. If the need to z-score after epoching arises in our analyses we can worry about the implementation then.

**Comment by shawntz** [comment]
sgtm!

**Comment by mh105** [comment]
My personal feel is that we don't need to enforce any steps prior to epoching. Some people might be interested in transients throughout the data or dynamics around blink periods. It should be fine to allow people to use `eyeris` just to epoch data.

To your comment about 
> another open question is how to handle requests to run steps after epoching, **_on the epoched data_**.

I think we should not support any action on epoched data right now. To me epoching is the division between preprocessing and analysis - at least right now you want `eyeris` to support preprocessing. If people choose to z-score each epoch, that to me is one way to analyze the data already even though z-score may feel like a preprocessing step. If we adhere to this rule of thumb we can streamline current code development a lot and focus on getting the preprocessing done well.

**Comment by shawntz** [comment]
thanks for your additional thoughts on this @mh105; i support this approach and will continue to adhere to this rule of thumb throughout development!
